# Generated by Django 3.0 on 2021-12-12 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileS3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, verbose_name='Ссылка')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners_file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл S3',
                'verbose_name_plural': 'Файлы S3',
            },
        ),
    ]
