# Generated by Django 3.0 on 2021-10-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type_name', models.CharField(choices=[('C', 'Cocktail'), ('D', 'Dish')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=256)),
                ('recipe_description', models.TextField(max_length=4000)),
                ('recipe_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.RecipeType')),
            ],
        ),
    ]
